Update build.yml
Update for concurrency

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -8,14 +8,23 @@ on:
   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
   
+# Only one concurrent action at a time for group tag.
+concurrency:
+  group: CI-Build-Development-${{ github.head_ref }}
+  cancel-in-progress: true
+
 jobs: 
   start-runner:
     runs-on: ubuntu-latest
     steps:
-      - name: Login 
+      - name: Output HeadRef
+        run: echo "${{ github.head_ref }}"
+        
+      - name: Azure Login 
         uses: azure/login@v1
         with:
-          creds: ${{ secrets.AZURE_CREDENTIALS }}     
+          creds: ${{ secrets.AZURE_CREDENTIALS }}
+          
       - name: Start self-hosted runner
         run: |
           az vm start --subscription Build -g Dev-CI -n github-runner1
@@ -40,16 +49,30 @@ jobs:
           docker exec -w /Development/Milestone3/Binary/ ubuntu_dev_CI ls -l
           docker stop ubuntu_dev_CI
           docker rm ubuntu_dev_CI
+  
   stop-runner:
+    if: always()
     runs-on: ubuntu-latest
-    needs: build
+    needs: [start-runner, build]
     steps:
-      - name: Login 
+      - name: Azure Login 
         uses: azure/login@v1
         with:
           creds: ${{ secrets.AZURE_CREDENTIALS }}
+
       - name: Deallocate self-hosted runner
         run: |
           pwd
           ls -l
           az vm deallocate  --subscription Build -g Dev-CI -n github-runner1 --no-wait
+  
+  workflow-conclusion:
+    # Without this step workflow remains "green" if build does fail.
+    if: always()
+    runs-on: ubuntu-latest
+    needs: [start-runner, build, stop-runner]
+    steps:
+      - uses: technote-space/workflow-conclusion-action@v2
+      - name: Check Job Status status and fail if they are red
+        if: env.WORKFLOW_CONCLUSION == 'failure'
+        run: exit 1
